services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=codeprompthub

    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
